export class ORM_HealthInformationCaptureAttachments
{
    attachment_id:String;
    patient_id:String;
    practice_id:String;
    document_date:String;
    name:String;
    original_file_name:String;
    link:String;
    health_info_id:String;
    attach_type:String;
    deleted:String;
    created_user:String;
    modified_user:String;
    date_created:String;
    client_date_created:String;
    date_modified:String;
    client_date_modified:String;
    system_ip:String;
}