export class ORMCognitiveFunctional {
    reasonforvisit_id:String;
    cognitive_functional_id:String;
	patient_id:String;
	chart_id:String;
	type:String;
	status:String;
	effective_date:String;
	snomed_code:String;
	snomed_description:String;
	deleted:Boolean;
	created_user:String;
	date_created:String;
	client_date_created:String;
	client_date_modified:String;
	modified_user:String;
	date_modified:String;
	practice_id:String;
	system_ip:String;
	notes:String;
}