export class ORMSaveSurgery {
    chart_procedures_id:String;
    chart_id:String;
    patient_id:String;
    procedure_code:String;
    description:String;
    procedure_date:String;
    practice_id:String;
    system_ip:String;
    deleted:Boolean;
    created_user:String;
    client_date_created:String;
    modified_user:String;
    client_date_modified:String;
    date_created:String;
    date_modified:String;
    comments:String;
    education_provided:Boolean;
    code_type:String;
    entry_type:String;
}